nameOverride: ""
fullnameOverride: ""

enabled: true

annotations: {}
ingressClassName: nginx

tls: []

rules:
  - host: example.local
    paths:
      - path: /
        pathType: Prefix
        service:
          name: example-frontend
          port: 80
